### ISSUE TITLE
Wordpress 4.4 responsive images

### ISSUE THREAD

**Issue by jimdavis66** [getsuzie/suzie#10]
Hi, is there an issue with responsive images and the S3 upload? 

When I add an image into a wordpress page or post the 'src' value is correct, but it still wants to use the non-S3 URL for 'srcset' value

`<img class="alignnone size-medium wp-image-8" src="https://s3-ap-southeast-2.amazonaws.com/assets.xyz.nsw.edu.au/content/uploads/2016/04/jon-219x300.jpg" alt="jon" width="219" height="300" srcset="http://dashboard-test.ap-southeast-2.elasticbeanstalk.com/content/uploads/2016/04/jon-219x300.jpg 219w, http://dashboard-test.ap-southeast-2.elasticbeanstalk.com/content/uploads/2016/04/jon.jpg 253w" sizes="(max-width: 219px) 100vw, 219px">`

Thanks!

**Comment by jasonagnew** [comment]
Sorry about this. It's sorted now in the new version
