### ISSUE TITLE
Composer managed plugins

### ISSUE THREAD

**Issue by borantula** [getsuzie/suzie#3]
Hello,

I installed a bunch of plugins via composer, they are in public/wordpress/content/plugins folder but they don't appear on the Plugins section of the site.

Is there any other setting should I do, I went through the docs but could find?

Thanks

**Comment by jasonagnew** [comment]
Hi @borantula 

There was mistake in the `composer.json`:

`"public/wordpress/content/plugins/{$name}/": ["type:wordpress-plugin"]`

should be 

`"public/content/plugins/{$name}/": ["type:wordpress-plugin"]`

Cheers

**Comment by borantula** [comment]
Thanks :) Meanwhile I tried a different solution below, it works but this is officially better of course :D  

cp -ans /var/www/dev.com/suzie/public/wordpress/content/plugins/\* /var/www/dev.com/suzie/public/content/plugins
