### ISSUE TITLE
.env.example is not cloned

### ISSUE THREAD

**Issue by ravaboard** [getsuzie/suzie#6]
Hi,

when I clone suzie with git I do not get all files that starts with a dot including .env.example even if I not see those files in the .git ignore file. How to make sure that .env.example would be cloned too? Thanks.

**Comment by jasonagnew** [comment]
Hi @ravaboard, depending on what OS your using .filename are normally hidden by default but visible in a code editor or in terminal. On mac or linux if go to terminal and find the directory you list everything by doing `ls -la`
